### ISSUE TITLE
gaps should not be applied to transient windows

### ISSUE THREAD

**Issue by jakecoble** [lepisma/swm-gaps#3]
Transient windows should not have gaps applied to them. This often causes them to shrink unusably small.

**Comment by lepisma** [comment]
Did you mean the transient windows like 
![image](https://user-images.githubusercontent.com/2487306/28233213-39eeb972-68c3-11e7-8dad-9fe87be12832.png) these ones (I can see the problem here with >0 inner gap) or windows from _floating group_? I believe floating group doesn't get any extra padding.

**Comment by jakecoble** [comment]
Ah, that explains why I wasn't able to fix the problem – I thought transient windows were a part of the floating group.

**Comment by lepisma** [comment]
3a79995 skips adding inner gaps to transients. When transient window gravity is set to `top`, something like the following happens.

 ![image](https://user-images.githubusercontent.com/2487306/28235950-4c6fde7c-68e7-11e7-88d5-f614af1bf6e9.png)

The correct way to fix this would be to check for transient window gravity and move the `y` value down if its `:top` (similarly for other alignments) to align things neatly. Will fix this soon.

**Comment by lepisma** [comment]
This issue was moved to stumpwm/stumpwm-contrib#75
