### ISSUE TITLE
Integrate swm-gaps into the codebase

### ISSUE THREAD

**Issue by dmb2** [lepisma/swm-gaps#4]
What would you think of either:
a. integrating this functionality into stumpwm proper
b. putting your module in stumpwm-contrib and having commit access to that repo to continue work?

**Comment by lepisma** [comment]
Sure. Though I am not sure about which of the options will fit better.

Since it redefines some core functions, it might be better to go with *a*. But then it can also be in contrib since gaps are not really essential to a wm.

**Comment by dmb2** [comment]
When you're ready (if you're willing) feel free to open a PR to stumpwm-contrib.  Even if it's just to add your module to the readme so users can find it, I would be happy.
